name: Build on Ubuntu

on:
  push:
    branches:
      - main
      - v*

    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt
      - CMakePresets.json

  pull_request:
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt
      - CMakePresets.json

jobs:
  build-ubuntu:
    name: ubuntu-${{ matrix.buildtype }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildtype: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Get latest CMake
        # Using 'latest' branch, the latest CMake is installed.
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: >
          sudo apt update -q &&
          sudo apt install -yq build-essential lua5.4 libmysqlclient-dev
          libboost-system-dev libboost-iostreams-dev
          libpugixml-dev libcrypto++-dev libfmt-dev

      - name: Build with cmake
        uses: lukka/run-cmake@v10
        with:
          buildPreset: default
          buildPresetAdditionalArgs: "['--config ${{ matrix.buildtype }}']"
          configurePreset: default

      - name: Upload artifact binary
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-tfs-amd64-${{ github.sha }}
          path: ${{ runner.workspace }}/build/tfs
